<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.26">

  <meta name="author" content="Paulo Fagandini">
  <meta name="dcterms.date" content="2026-01-01">
  <title>Economics of Tourism – Aggregation: The Concept</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-e109428474854d908f205605d54b47e4.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Aggregation: The Concept</h1>
  <p class="subtitle">Lecture 21: From Individual Transactions to the Economy as a Whole</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Paulo Fagandini 
</div>
</div>
</div>

  <p class="date">2026</p>
</section>
<section id="recap-the-macro-panorama" class="slide level2">
<h2>Recap: The Macro Panorama <span class="emoji" data-emoji="rewind">⏪</span></h2>
<p>Last lecture we identified the <strong>six big macroeconomic issues</strong>:</p>
<div class="columns">
<div class="column" style="width:50%;">
<p><span class="emoji" data-emoji="seedling">🌱</span> Economic growth &amp; living standards</p>
<p><span class="emoji" data-emoji="factory">🏭</span> Productivity</p>
<p><span class="emoji" data-emoji="roller_coaster">🎢</span> Recessions &amp; expansions</p>
</div><div class="column" style="width:50%;">
<p><span class="emoji" data-emoji="briefcase">💼</span> Unemployment</p>
<p><span class="emoji" data-emoji="fire">🔥</span> Inflation</p>
<p><span class="emoji" data-emoji="globe_with_meridians">🌐</span> International interdependence</p>
</div></div>
<div class="fragment">
<p>To study all of these, we need one fundamental tool:</p>
<p><span class="emoji" data-emoji="point_right">👉</span> <strong>Aggregation</strong> — summing up millions of individual decisions into a single economy-wide picture.</p>
</div>
</section>
<section>
<section id="part-i-what-is-aggregation" class="title-slide slide level1 center">
<h1>Part I: What is Aggregation?</h1>

</section>
<section id="the-problem-of-scale" class="slide level2">
<h2>The Problem of Scale <span class="emoji" data-emoji="microscope">🔬</span></h2>
<p>In microeconomics, we studied <strong>one consumer</strong>, <strong>one firm</strong>, <strong>one market</strong>.</p>
<div class="fragment">
<p>But Portugal has:</p>
<div class="columns">
<div class="column" style="width:50%;">
<p><span class="emoji" data-emoji="busts_in_silhouette">👥</span> ~10 million consumers</p>
<p><span class="emoji" data-emoji="factory">🏭</span> ~1.3 million registered firms</p>
<p><span class="emoji" data-emoji="handshake">🤝</span> Billions of transactions per year</p>
<p><span class="emoji" data-emoji="hotel">🏨</span> ~8,000 hotels and similar accommodations</p>
</div><div class="column" style="width:50%;">
<p>We cannot track every transaction. We need a way to <strong>compress</strong> all of this information into a manageable set of numbers.</p>
<p><span class="emoji" data-emoji="point_right">👉</span> That is exactly what <strong>aggregation</strong> does.</p>
</div></div>
</div>
</section>
<section id="what-is-aggregation" class="slide level2">
<h2>What is Aggregation? <span class="emoji" data-emoji="jigsaw">🧩</span></h2>
<div class="key-concept">
<p><strong>Aggregation</strong> is the process of <strong>summing individual economic variables</strong> — the spending decisions of millions of households, the output of thousands of firms — to obtain <strong>totals for the economy as a whole</strong>.</p>
</div>
<div class="fragment">
<p><strong>Examples:</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Individual variable</th>
<th>Aggregate variable</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Ana spends €80/month on restaurant meals</td>
<td>Household consumption</td>
</tr>
<tr class="even">
<td>Pestana Hotels invests in a new resort</td>
<td>Business investment</td>
</tr>
<tr class="odd">
<td>Portuguese government builds a new highway</td>
<td>Government expenditure</td>
</tr>
<tr class="even">
<td>A Lisbon hotel sells rooms to German tourists</td>
<td>Exports of services</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="why-does-aggregation-work" class="slide level2">
<h2>Why Does Aggregation Work? <span class="emoji" data-emoji="thinking">🤔</span></h2>
<p>Aggregation works because — even though individuals differ — their <strong>combined behaviour</strong> follows <strong>predictable patterns</strong>.</p>
<div class="fragment">
<div class="columns">
<div class="column" style="width:55%;">
<p>Think of a <strong>thermometer</strong> <span class="emoji" data-emoji="thermometer">🌡️</span></p>
<p>You cannot track every molecule of air in this room individually. But the <strong>average kinetic energy</strong> of all molecules gives you a reliable, useful number: <strong>temperature</strong>.</p>
<p>Similarly, we cannot track every euro spent in Portugal. But the <strong>sum of all spending</strong> gives us a reliable number: <strong>GDP</strong>.</p>
</div><div class="column" style="width:45%;">
<p><span class="emoji" data-emoji="bulb">💡</span> <strong>Key insight:</strong></p>
<p>Individual details get “averaged out”. What remains is the <strong>systematic, predictable</strong> part of economic behaviour — which is exactly what policy needs to respond to.</p>
<p><span class="emoji" data-emoji="warning">⚠️</span> <strong>The cost:</strong> Aggregation hides <strong>distribution</strong> — who gets what.</p>
</div></div>
</div>
</section>
<section id="the-trade-off-of-aggregation" class="slide level2">
<h2>The Trade-off of Aggregation <span class="emoji" data-emoji="balance_scale">⚖️</span></h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><span class="emoji" data-emoji="heavy_check_mark">✔️</span> <strong>What aggregation gives us:</strong></p>
<ul>
<li>A manageable picture of the whole economy</li>
<li>Comparisons across time and countries</li>
<li>Targets for economic policy</li>
<li>Early warning indicators (recessions, inflation)</li>
</ul>
</div><div class="column" style="width:50%;">
<p><span class="emoji" data-emoji="warning">⚠️</span> <strong>What aggregation hides:</strong></p>
<ul>
<li>Inequality: who earns the income?</li>
<li>Regional differences: Lisbon vs interior Portugal</li>
<li>Sectoral differences: tourism booming while manufacturing shrinks</li>
<li>Quality of jobs: full-time vs precarious seasonal work</li>
</ul>
</div></div>
<div class="fragment">
<p><span class="emoji" data-emoji="point_right">👉</span> A country’s GDP can grow while most workers see their wages <strong>fall</strong> — if growth is concentrated at the top. Aggregation alone does not tell us this.</p>
</div>
</section></section>
<section>
<section id="part-ii-the-circular-flow-of-income" class="title-slide slide level1 center">
<h1>Part II: The Circular Flow of Income</h1>

</section>
<section id="economies-as-a-flow" class="slide level2">
<h2>Economies as a Flow <span class="emoji" data-emoji="recycle">♻️</span></h2>
<p>The best way to understand aggregation is through the <strong>circular flow of income</strong> model.</p>
<div class="fragment">
<div class="key-concept">
<p>The <strong>circular flow model</strong> shows how money, goods, and services continuously flow between the main economic agents — households, firms, the government, and the rest of the world.</p>
</div>
</div>
<div class="fragment">
<p>We will build it up <strong>step by step</strong>, starting simple and adding complexity.</p>
</div>
</section>
<section id="step-1-two-agents-households-firms" class="slide level2">
<h2>Step 1: Two Agents — Households &amp; Firms <span class="emoji" data-emoji="arrows_counterclockwise">🔄</span></h2>
<div class="columns">
<div class="column" style="width:55%;">
<p>In the simplest economy:</p>
<p><strong>Households</strong> <span class="emoji" data-emoji="family">👪</span></p>
<ul>
<li>Own the factors of production (labour, capital, land)</li>
<li>Sell them to firms → earn <strong>income</strong></li>
<li>Spend that income on goods and services → <strong>consumption</strong></li>
</ul>
<p><strong>Firms</strong> <span class="emoji" data-emoji="factory">🏭</span></p>
<ul>
<li>Buy factors of production → pay <strong>wages, rents, profits</strong></li>
<li>Produce goods and services → earn <strong>revenue</strong></li>
</ul>
<p><span class="emoji" data-emoji="point_right">👉</span> Money flows in a <strong>circle</strong>: from firms to households (as income), and back from households to firms (as spending).</p>
</div><div class="column" style="width:45%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="lecture21-aggregation_files/figure-revealjs/unnamed-chunk-2-1.png" width="480"></p>
</figure>
</div>
</div>
</div>
</div></div>
</section>
<section id="step-2-adding-the-government" class="slide level2">
<h2>Step 2: Adding the Government <span class="emoji" data-emoji="classical_building">🏛️</span></h2>
<p>In a real economy, the <strong>government</strong> plays a major role:</p>
<div class="fragment">
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Government collects:</strong></p>
<p><span class="emoji" data-emoji="moneybag">💰</span> <strong>Taxes</strong> — from households (income tax) and firms (corporate tax)</p>
<p><strong>Government spends:</strong></p>
<p><span class="emoji" data-emoji="school">🏫</span> Public services — education, health, infrastructure</p>
<p><span class="emoji" data-emoji="handshake">🤝</span> <strong>Transfer payments</strong> — pensions, unemployment benefits (money back to households without a service in return)</p>
</div><div class="column" style="width:50%;">
<p><strong>Key implication:</strong></p>
<p>Not all household income is spent on consumption. Some leaks out as <strong>taxes</strong>.</p>
<p>Not all firm revenue stays in the private sector. Government <strong>injects</strong> spending back in.</p>
<p><span class="emoji" data-emoji="point_right">👉</span> The flow is still circular, but the government acts as a <strong>redistribution node</strong>.</p>
</div></div>
</div>
</section>
<section id="step-3-adding-the-rest-of-the-world" class="slide level2">
<h2>Step 3: Adding the Rest of the World <span class="emoji" data-emoji="globe_with_meridians">🌐</span></h2>
<p>Real economies also trade with the outside world:</p>
<div class="fragment">
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Exports</strong> <span class="emoji" data-emoji="outbox_tray">📤</span></p>
<p>Foreigners buy Portuguese goods and services</p>
<p><span class="emoji" data-emoji="point_right">👉</span> Money <strong>flows in</strong> to Portugal</p>
<p>For tourism: foreign visitors spending in Portuguese hotels, restaurants, attractions = <strong>export of services</strong></p>
<p><strong>Imports</strong> <span class="emoji" data-emoji="inbox_tray">📥</span></p>
<p>Portuguese households and firms buy foreign goods</p>
<p><span class="emoji" data-emoji="point_right">👉</span> Money <strong>flows out</strong> of Portugal</p>
</div><div class="column" style="width:50%;">
<div class="key-concept">
<p><strong>Net Exports (NX)</strong></p>
<p><span class="math display">\[NX = \text{Exports} - \text{Imports}\]</span></p>
<p>If NX &gt; 0: more money flowing <strong>in</strong> than out (trade surplus)</p>
<p>If NX &lt; 0: more money flowing <strong>out</strong> than in (trade deficit)</p>
</div>
<p>Portugal typically runs a <strong>services surplus</strong> (tourism!) but a <strong>goods deficit</strong>.</p>
</div></div>
</div>
</section>
<section id="the-full-circular-flow" class="slide level2">
<h2>The Full Circular Flow <span class="emoji" data-emoji="earth_africa">🌍</span></h2>
<div class="columns">
<div class="column" style="width:58%;">
<p>The complete model has <strong>four agents</strong> and <strong>four types of spending</strong>:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Agent</th>
<th>Type of spending</th>
<th>Symbol</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Households</td>
<td>Consumption</td>
<td>C</td>
</tr>
<tr class="even">
<td>Firms</td>
<td>Investment</td>
<td>I</td>
</tr>
<tr class="odd">
<td>Government</td>
<td>Government expenditure</td>
<td>G</td>
</tr>
<tr class="even">
<td>Rest of world</td>
<td>Net exports</td>
<td>NX</td>
</tr>
</tbody>
</table>
<p>. . .</p>
<p><strong>The fundamental identity:</strong></p>
<p><span class="math display">\[Y = C + I + G + NX\]</span></p>
<p><span class="emoji" data-emoji="point_right">👉</span> Every euro of output produced in Portugal must be <strong>purchased</strong> by someone — this equation always holds, by definition. This is the <strong>expenditure approach</strong> to GDP (next lecture).</p>
</div><div class="column" style="width:42%;">
<p><strong>Leakages vs Injections</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Leakages <span class="emoji" data-emoji="outbox_tray">📤</span></th>
<th>Injections <span class="emoji" data-emoji="inbox_tray">📥</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Savings (S)</td>
<td>Investment (I)</td>
</tr>
<tr class="even">
<td>Taxes (T)</td>
<td>Government spending (G)</td>
</tr>
<tr class="odd">
<td>Imports (M)</td>
<td>Exports (X)</td>
</tr>
</tbody>
</table>
<p>In equilibrium:</p>
<p><span class="math display">\[S + T + M = I + G + X\]</span></p>
<p><span class="emoji" data-emoji="bulb">💡</span> What leaks out of the circular flow must be matched by injections back in.</p>
</div></div>
</section></section>
<section>
<section id="part-iii-aggregating-output-what-counts" class="title-slide slide level1 center">
<h1>Part III: Aggregating Output — What Counts?</h1>

</section>
<section id="the-value-added-principle" class="slide level2">
<h2>The Value-Added Principle <span class="emoji" data-emoji="link">🔗</span></h2>
<p>When we aggregate output, we face a problem: <strong>double counting</strong>.</p>
<div class="fragment">
<p><strong>Example — a tourist breakfast in Porto:</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Stage</th>
<th>Seller</th>
<th>Revenue</th>
<th>Cost of inputs</th>
<th><strong>Value Added</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Wheat farm</td>
<td>Farmer</td>
<td>€0.50</td>
<td>€0</td>
<td><strong>€0.50</strong></td>
</tr>
<tr class="even">
<td>Flour mill</td>
<td>Miller</td>
<td>€1.20</td>
<td>€0.50</td>
<td><strong>€0.70</strong></td>
</tr>
<tr class="odd">
<td>Bakery</td>
<td>Baker</td>
<td>€2.00</td>
<td>€1.20</td>
<td><strong>€0.80</strong></td>
</tr>
<tr class="even">
<td><strong>Total GDP contribution</strong></td>
<td></td>
<td></td>
<td></td>
<td><strong>€2.00</strong></td>
</tr>
</tbody>
</table>
</div>
<div class="fragment">
<p><span class="emoji" data-emoji="point_right">👉</span> We <strong>do not</strong> add €0.50 + €1.20 + €2.00 = €3.70 (that would count the bread three times).</p>
<p>We add only the <strong>value added</strong> at each stage: €0.50 + €0.70 + €0.80 = <strong>€2.00</strong>.</p>
</div>
</section>
<section id="what-gets-included-in-aggregation" class="slide level2">
<h2>What Gets Included in Aggregation? <span class="emoji" data-emoji="white_check_mark">✅</span></h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><span class="emoji" data-emoji="heavy_check_mark">✔️</span> <strong>Included:</strong></p>
<ul>
<li>Final goods and services (sold to end users)</li>
<li>Government services (at cost)</li>
<li>New housing construction</li>
<li>Changes in business inventories</li>
<li>Exports of goods and services</li>
</ul>
<p><span class="emoji" data-emoji="hotel">🏨</span> <em>A German tourist staying at a Lisbon hotel: the room rate is included as an <strong>export of services</strong>.</em></p>
</div><div class="column" style="width:50%;">
<p><span class="emoji" data-emoji="x">❌</span> <strong>Not included:</strong></p>
<ul>
<li>Intermediate goods (used to produce other goods)</li>
<li>Sales of existing assets (second-hand house sales)</li>
<li>Financial transactions (buying shares)</li>
<li>Transfer payments (pensions, subsidies)</li>
<li>Unpaid work (home cooking, volunteering)</li>
</ul>
<p><span class="emoji" data-emoji="thinking">🤔</span> <em>Why not second-hand houses? The house was already counted when it was first built.</em></p>
</div></div>
</section>
<section id="the-tourism-aggregation-problem" class="slide level2">
<h2>The Tourism Aggregation Problem <span class="emoji" data-emoji="beach_umbrella">🏖️</span></h2>
<p>Tourism is a <strong>cross-cutting industry</strong> — it does not have a single production line. This makes aggregation tricky.</p>
<div class="fragment">
<div class="columns">
<div class="column" style="width:55%;">
<p>When a British tourist spends €1,000 in Portugal:</p>
<ul>
<li>€350 at hotels <span class="emoji" data-emoji="hotel">🏨</span> → counted under <strong>accommodation services</strong></li>
<li>€200 at restaurants <span class="emoji" data-emoji="fork_and_knife">🍴</span> → counted under <strong>food &amp; beverage</strong></li>
<li>€150 on transport <span class="emoji" data-emoji="bus">🚌</span> → counted under <strong>transport services</strong></li>
<li>€200 on retail :shopping_bags: → counted under <strong>retail trade</strong></li>
<li>€100 on cultural attractions <span class="emoji" data-emoji="performing_arts">🎭</span> → counted under <strong>arts &amp; entertainment</strong></li>
</ul>
<p><span class="emoji" data-emoji="point_right">👉</span> That €1,000 is <strong>spread across multiple sectors</strong> in the national accounts. There is no single “tourism line” in GDP — it must be reconstructed using <strong>Tourism Satellite Accounts (TSA)</strong>.</p>
</div><div class="column" style="width:45%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="lecture21-aggregation_files/figure-revealjs/unnamed-chunk-3-1.png" width="460"></p>
</figure>
</div>
</div>
</div>
</div></div>
</div>
</section>
<section id="tourisms-share-in-the-portuguese-economy" class="slide level2">
<h2>Tourism’s Share in the Portuguese Economy <span class="emoji" data-emoji="portugal">🇵🇹</span></h2>

<img data-src="lecture21-aggregation_files/figure-revealjs/unnamed-chunk-4-1.png" width="1056" class="r-stretch"><p><span class="emoji" data-emoji="point_right">👉</span> Tourism represents a <strong>significant and growing share</strong> of Portugal’s GDP — making macroeconomic performance especially important for this industry.</p>
</section></section>
<section>
<section id="part-iv-aggregate-demand-and-aggregate-supply" class="title-slide slide level1 center">
<h1>Part IV: Aggregate Demand and Aggregate Supply</h1>

</section>
<section id="from-individual-to-aggregate-curves" class="slide level2">
<h2>From Individual to Aggregate Curves <span class="emoji" data-emoji="chart_with_upwards_trend">📈</span></h2>
<p>In microeconomics we drew <strong>individual demand</strong> and <strong>supply curves</strong> for single markets.</p>
<p>In macroeconomics we aggregate these into:</p>
<div class="fragment">
<div class="columns">
<div class="column" style="width:50%;">
<p><span class="emoji" data-emoji="shopping_cart">🛒</span> <strong>Aggregate Demand (AD)</strong></p>
<p>The total demand for all goods and services in an economy at each <strong>price level</strong>.</p>
<p><span class="math display">\[AD = C + I + G + NX\]</span></p>
<p>Downward sloping: when prices rise, real purchasing power falls, real wealth falls, and exports become less competitive.</p>
</div><div class="column" style="width:50%;">
<p><span class="emoji" data-emoji="factory">🏭</span> <strong>Aggregate Supply (AS)</strong></p>
<p>The total output all firms in an economy are willing to produce at each <strong>price level</strong>.</p>
<p>Upward sloping in the <strong>short run</strong>: higher prices make production more profitable.</p>
<p>Vertical in the <strong>long run</strong>: output is determined by real factors (technology, labour, capital), not prices.</p>
</div></div>
</div>
</section>
<section id="the-ad-as-model-preview" class="slide level2">
<h2>The AD-AS Model (Preview) <span class="emoji" data-emoji="bar_chart">📊</span></h2>

<img data-src="lecture21-aggregation_files/figure-revealjs/unnamed-chunk-5-1.png" width="960" class="r-stretch"><p><span class="emoji" data-emoji="point_right">👉</span> This model gives us the macroeconomic equivalent of the supply-demand diagram we used in microeconomics. We will use it throughout the macro block.</p>
</section>
<section id="the-three-approaches-to-measuring-aggregate-output" class="slide level2">
<h2>The Three Approaches to Measuring Aggregate Output <span class="emoji" data-emoji="straight_ruler">📏</span></h2>
<p>Any economy can be measured from <strong>three equivalent angles</strong> — they always give the same answer:</p>
<div class="fragment">
<div class="columns">
<div class="column" style="width:33%;">
<p><span class="emoji" data-emoji="outbox_tray">📤</span> <strong>Expenditure approach</strong></p>
<p>Add up all <strong>spending</strong> on final goods and services</p>
<p><span class="math display">\[Y = C + I + G + NX\]</span></p>
<p><em>Who buys the output?</em></p>
</div><div class="column" style="width:33%;">
<p><span class="emoji" data-emoji="incoming_envelope">📨</span> <strong>Income approach</strong></p>
<p>Add up all <strong>incomes</strong> earned in production</p>
<p><span class="math display">\[Y = W + R + \Pi + \text{taxes}\]</span></p>
<p><em>(Wages + Rents + Profits)</em></p>
<p><em>Who earns from production?</em></p>
</div><div class="column" style="width:33%;">
<p><span class="emoji" data-emoji="factory">🏭</span> <strong>Production (value-added) approach</strong></p>
<p>Add up <strong>value added</strong> at each stage of production</p>
<p><span class="math display">\[Y = \sum \text{Value Added}\]</span></p>
<p><em>What is produced?</em></p>
</div></div>
</div>
<div class="fragment">
<p><span class="emoji" data-emoji="bulb">💡</span> All three approaches measure the <strong>same thing</strong> — total economic activity — just from different perspectives. Next lecture we focus on the expenditure approach: <strong>GDP</strong>.</p>
</div>
</section></section>
<section>
<section id="exercises" class="title-slide slide level1 center">
<h1>Exercises</h1>

</section>
<section id="exercise-1-multiple-choice" class="slide level2">
<h2><span class="emoji" data-emoji="pencil">📝</span> Exercise 1 — Multiple Choice</h2>
<p><strong>A local tour operator in the Algarve buys sunscreen bottles from a wholesaler for €4 each, and sells them to tourists for €7 each. What is the value added by the tour operator, and how much does this contribute to GDP?</strong></p>
<div class="fragment">
<p><strong>(A)</strong> €7 — the full selling price is GDP</p>
<p><strong>(B)</strong> €4 — only intermediate costs count</p>
<p><strong>(C)</strong> €3 — only the value added by the tour operator counts</p>
<p><strong>(D)</strong> €11 — the sum of all transactions counts</p>
<div class="fragment">
<div class="highlight-box">
<p><strong>Correct answer: (C)</strong></p>
<p>The tour operator’s <strong>value added</strong> = €7 − €4 = <strong>€3</strong>. GDP counts only value added at each stage to avoid double-counting. The €4 paid to the wholesaler was already (or will be) counted as the wholesaler’s value added. Option A double-counts the wholesale stage; D triple-counts it.</p>
</div>
</div>
</div>
</section>
<section id="exercise-2-multiple-choice" class="slide level2">
<h2><span class="emoji" data-emoji="pencil">📝</span> Exercise 2 — Multiple Choice</h2>
<p><strong>Which of the following transactions would NOT be included in Portugal’s GDP?</strong></p>
<div class="fragment">
<p><strong>(A)</strong> A German tourist pays €150 to stay in a Porto hotel</p>
<p><strong>(B)</strong> The Portuguese government pays €2,000/month in pensions to a retired teacher</p>
<p><strong>(C)</strong> A new Airbus A320 is purchased by TAP Air Portugal for its fleet</p>
<p><strong>(D)</strong> A Portuguese construction company builds 10 new apartments</p>
<div class="fragment">
<div class="highlight-box">
<p><strong>Correct answer: (B)</strong></p>
<p><strong>Transfer payments</strong> (pensions, unemployment benefits) are <strong>not</strong> included in GDP — they redistribute existing income but do not correspond to new production of goods or services. Option A is an export of services (counted). Option C is investment (counted). Option D is investment in new construction (counted).</p>
</div>
</div>
</div>
</section>
<section id="exercise-3-open-question" class="slide level2">
<h2><span class="emoji" data-emoji="pencil">📝</span> Exercise 3 — Open Question</h2>
<p><strong>Consider a simplified tourism economy with three firms:</strong></p>
<ul>
<li><strong>Quinta do Algarve</strong> (wine producer): sells wine to a restaurant for <strong>€60</strong>. Inputs from outside the economy cost <strong>€10</strong>.</li>
<li><strong>Restaurante Praia</strong> (restaurant): buys wine for €60 and other ingredients for €20, and sells meals to tourists for <strong>€160</strong>.</li>
<li><strong>Hotel Maré</strong> (hotel): builds a new outdoor terrace at a cost of <strong>€500</strong> (inputs purchased from local suppliers for <strong>€300</strong>, rest is labour).</li>
</ul>
<p><strong>(a)</strong> Calculate the <strong>value added</strong> by each firm. <em>(3 marks)</em></p>
<p><strong>(b)</strong> What is the <strong>total contribution to GDP</strong> of these three firms? <em>(2 marks)</em></p>
<p><strong>(c)</strong> To which component of GDP (C, I, G, or NX) does each transaction belong? Justify briefly. <em>(3 marks)</em></p>
<p><strong>(d)</strong> If the meals at Restaurante Praia were purchased exclusively by <strong>foreign tourists</strong>, how would your classification in (c) change? <em>(2 marks)</em></p>
</section>
<section class="slide level2">

<div class="fragment">
<p><strong>Solution:</strong></p>
<p><strong>(a)</strong> - Quinta do Algarve: €60 − €10 = <strong>€50</strong> - Restaurante Praia: €160 − €60 − €20 = <strong>€80</strong> - Hotel Maré: €500 − €300 = <strong>€200</strong> (value of new terrace less purchased inputs)</p>
<p><strong>(b)</strong> Total GDP contribution = €50 + €80 + €200 = <strong>€330</strong></p>
<p><strong>(c)</strong> Restaurant meals sold to domestic consumers → <strong>C</strong> (consumption). Hotel terrace construction → <strong>I</strong> (investment, as it is a new capital asset). Wine sold to the restaurant is an intermediate good → <strong>not counted directly</strong> (captured via value added).</p>
<p><strong>(d)</strong> If meals are purchased by foreign tourists, they represent an <strong>export of services</strong> → classified under <strong>NX</strong> (net exports), not C. The money flows <strong>into</strong> Portugal from abroad.</p>
</div>
</section>
<section id="summary" class="slide level2">
<h2>Summary <span class="emoji" data-emoji="books">📚</span></h2>
<p><strong>Today we covered:</strong></p>
<p><span class="emoji" data-emoji="white_check_mark">✅</span> <strong>Aggregation</strong> — summing individual variables into economy-wide totals</p>
<p><span class="emoji" data-emoji="white_check_mark">✅</span> The <strong>circular flow of income</strong> — households, firms, government, and the rest of the world</p>
<p><span class="emoji" data-emoji="white_check_mark">✅</span> <strong>Leakages</strong> (savings, taxes, imports) and <strong>injections</strong> (investment, government spending, exports)</p>
<p><span class="emoji" data-emoji="white_check_mark">✅</span> The <strong>value-added principle</strong> — how to avoid double counting</p>
<p><span class="emoji" data-emoji="white_check_mark">✅</span> What is and is not <strong>included</strong> in aggregate output</p>
<p><span class="emoji" data-emoji="white_check_mark">✅</span> The <strong>three approaches</strong> to measuring output (expenditure, income, production)</p>
<div class="fragment">
<p><strong>Next lecture (Lecture 22):</strong></p>
<p><span class="emoji" data-emoji="mag">🔍</span> GDP in depth — the expenditure approach, nominal vs real GDP, and what GDP tells us (and doesn’t tell us) about well-being.</p>
</div>
</section>
<section id="thank-you" class="slide level2 center">
<h2>Thank You! <span class="emoji" data-emoji="wave">👋</span></h2>
<p><strong>Questions?</strong></p>
<p><span class="emoji" data-emoji="email">📧</span> paulo.fagandini@ext.universidadeeuropeia.pt</p>
</section>
<section class="slide level2">

<p><em>Next class: Friday, May 8th, 2026</em></p>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="../images/logo.png" class="slide-logo"></p>
<div class="footer footer-default">
<p>Economics of Tourism | Lecture 21</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1600,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>