<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.26">

  <meta name="author" content="Paulo Fagandini">
  <meta name="dcterms.date" content="2026-01-01">
  <title>Economics of Tourism – Producer Theory</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-e109428474854d908f205605d54b47e4.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Producer Theory</h1>
  <p class="subtitle">Lecture 10: The Geometry of Costs — Short Run vs Long Run</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Paulo Fagandini 
</div>
</div>
</div>

  <p class="date">2026</p>
</section>
<section id="welcome-back" class="slide level2 center">
<h2>Welcome Back! <span class="emoji" data-emoji="wave">👋</span></h2>
<p><strong>We’ve crossed the aisle:</strong></p>
<p><span class="emoji" data-emoji="shopping_cart">🛒</span> Lectures 5–9: <strong>Consumer Theory</strong> (demand side)</p>
<p><span class="emoji" data-emoji="factory">🏭</span> Lectures 10–17: <strong>Producer Theory</strong> (supply side)</p>
<div class="fragment">
<p><span class="emoji" data-emoji="dart">🎯</span> <strong>Today’s Goal</strong>: Understand the <strong>cost structure</strong> of firms</p>
<p>How do costs behave as production changes?</p>
</div>
</section>
<section>
<section id="from-consumer-to-producer" class="title-slide slide level1 center">
<h1>From Consumer to Producer</h1>

</section>
<section id="the-other-side-of-the-market" class="slide level2">
<h2>The Other Side of the Market <span class="emoji" data-emoji="handshake">🤝</span></h2>
<div style="font-size: 82%;">
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Consumer</strong> (Lectures 5–9):</p>
<ul>
<li>Maximizes <strong>utility</strong> <span class="emoji" data-emoji="chart_with_upwards_trend">📈</span></li>
<li>Subject to <strong>budget constraint</strong></li>
<li>Generates <strong>demand curves</strong></li>
<li>Tools: indifference curves, MRS, budget line</li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>Producer</strong> (Lectures 10–17):</p>
<ul>
<li>Maximizes <strong>profit</strong> <span class="emoji" data-emoji="moneybag">💰</span></li>
<li>Subject to <strong>cost structure</strong></li>
<li>Generates <strong>supply curves</strong></li>
<li>Tools: cost curves, marginal analysis</li>
</ul>
</div></div>
<p>. . .</p>
<p><span class="emoji" data-emoji="bulb">💡</span> <strong>Key parallel</strong>: Just as consumers face trade-offs with limited income, producers face trade-offs with limited resources and technology.</p>
</div>
</section>
<section id="the-producers-problem" class="slide level2">
<h2>The Producer’s Problem <span class="emoji" data-emoji="factory">🏭</span></h2>
<div style="font-size: 82%;">
<div class="key-concept">
<p><strong>The Producer’s Goal</strong></p>
<p>A firm wants to <strong>maximize profit</strong>. To do so, it must understand its costs at every level of output.</p>
<p><span class="math display">\[\pi = \text{Total Revenue} - \text{Total Cost} = TR - TC\]</span></p>
</div>
<p><strong>Before we can find the profit-maximizing quantity (next lecture), we need to master costs.</strong></p>
<p>Today we answer:</p>
<ul>
<li><span class="emoji" data-emoji="one">1️⃣</span> What types of costs does a firm face?</li>
<li><span class="emoji" data-emoji="two">2️⃣</span> How do costs change as output increases?</li>
<li><span class="emoji" data-emoji="three">3️⃣</span> What is the difference between short run and long run?</li>
</ul>
</div>
</section></section>
<section>
<section id="short-run-vs-long-run" class="title-slide slide level1 center">
<h1>Short Run vs Long Run</h1>

</section>
<section id="defining-the-time-horizons" class="slide level2">
<h2>Defining the Time Horizons <span class="emoji" data-emoji="hourglass_flowing_sand">⏳</span></h2>
<div style="font-size: 80%;">
<div class="key-concept">
<p><strong>Short Run vs Long Run</strong></p>
<p><strong>Short run</strong>: A period in which <strong>at least one</strong> factor of production is <strong>fixed</strong> (cannot be changed). Typically, capital (machines, buildings) is fixed.</p>
<p><strong>Long run</strong>: A period long enough that <strong>all</strong> factors of production are <strong>variable</strong>. The firm can adjust everything: equipment, factory size, workforce.</p>
</div>
<div class="columns">
<div class="column" style="width:50%;">
<p><span class="emoji" data-emoji="lock">🔒</span> <strong>Short Run</strong> — Tourism example:</p>
<p>A hotel has 100 rooms. It <strong>cannot build more rooms</strong> this season. It can only hire/fire staff (variable input).</p>
</div><div class="column" style="width:50%;">
<p><span class="emoji" data-emoji="unlock">🔓</span> <strong>Long Run</strong> — Tourism example:</p>
<p>The hotel chain can build a <strong>new wing</strong>, open in a <strong>new city</strong>, or <strong>exit</strong> the market entirely.</p>
</div></div>
</div>
</section>
<section id="inputs-fixed-vs-variable" class="slide level2">
<h2>Inputs: Fixed vs Variable <span class="emoji" data-emoji="wrench">🔧</span></h2>
<div style="font-size: 80%;">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th><strong>Fixed Inputs</strong> <span class="emoji" data-emoji="lock">🔒</span></th>
<th><strong>Variable Inputs</strong> <span class="emoji" data-emoji="arrows_counterclockwise">🔄</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Definition</strong></td>
<td>Cannot change in the short run</td>
<td>Can be adjusted at any time</td>
</tr>
<tr class="even">
<td><strong>Examples</strong></td>
<td>Building, machines, lease contracts</td>
<td>Workers, raw materials, energy</td>
</tr>
<tr class="odd">
<td><strong>Tourism</strong></td>
<td>Hotel building, aircraft, kitchen equipment</td>
<td>Staff, food supplies, fuel</td>
</tr>
<tr class="even">
<td><strong>Cost behavior</strong></td>
<td>Same cost regardless of output</td>
<td>Cost changes with output</td>
</tr>
</tbody>
</table>
<p>. . .</p>
<div class="key-concept">
<p><strong>The Key Distinction</strong></p>
<p>In the <strong>short run</strong>, the firm has both fixed and variable inputs. In the <strong>long run</strong>, <strong>all</strong> inputs are variable — there are no fixed costs.</p>
</div>
</div>
</section>
<section id="the-law-of-diminishing-returns" class="slide level2">
<h2>The Law of Diminishing Returns <span class="emoji" data-emoji="chart_with_downwards_trend">📉</span></h2>
<div style="font-size: 78%;">
<div class="key-concept">
<p><strong>Law of Diminishing Returns</strong></p>
<p>When we keep adding more of a <strong>variable input</strong> (e.g., workers) to a <strong>fixed input</strong> (e.g., a kitchen), eventually each additional worker adds <strong>less and less</strong> to total output.</p>
</div>
<p><strong>Tourism example</strong>: A restaurant kitchen with 5 stoves :cooking:</p>
<table class="caption-top">
<caption>bulb: <strong>Why?</strong> The fixed input (kitchen space) gets <strong>congested</strong>. Chefs bump into each other, wait for stoves, compete for prep space.</caption>
<thead>
<tr class="header">
<th style="text-align: center;">Extra chefs hired</th>
<th style="text-align: center;">Extra meals/hour produced</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1st chef</td>
<td style="text-align: center;">+30 meals</td>
</tr>
<tr class="even">
<td style="text-align: center;">2nd chef</td>
<td style="text-align: center;">+25 meals</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3rd chef</td>
<td style="text-align: center;">+18 meals</td>
</tr>
<tr class="even">
<td style="text-align: center;">4th chef</td>
<td style="text-align: center;">+10 meals</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5th chef</td>
<td style="text-align: center;">+4 meals (kitchen is crowded!)</td>
</tr>
</tbody>
</table>
</div>
</section></section>
<section>
<section id="types-of-costs-in-the-short-run" class="title-slide slide level1 center">
<h1>Types of Costs in the Short Run</h1>

</section>
<section id="the-cost-family" class="slide level2">
<h2>The Cost Family <span class="emoji" data-emoji="family">👪</span></h2>
<div style="font-size: 78%;">
<p><strong>All short-run costs derive from three building blocks:</strong></p>
<div class="columns">
<div class="column" style="width:33%;">
<p><span class="emoji" data-emoji="lock">🔒</span> <strong>Fixed Cost (FC)</strong></p>
<p>Costs that <strong>do not change</strong> with output.</p>
<p>Must be paid even if <span class="math inline">\(Q = 0\)</span>.</p>
<p><em>Hotel</em>: mortgage, insurance, property tax</p>
</div><div class="column" style="width:33%;">
<p><span class="emoji" data-emoji="arrows_counterclockwise">🔄</span> <strong>Variable Cost (VC)</strong></p>
<p>Costs that <strong>change</strong> with the level of output.</p>
<p>Zero when <span class="math inline">\(Q = 0\)</span>.</p>
<p><em>Hotel</em>: staff wages, laundry, food, energy</p>
</div><div class="column" style="width:34%;">
<p><span class="emoji" data-emoji="heavy_plus_sign">➕</span> <strong>Total Cost (TC)</strong></p>
<p>The sum of all costs.</p>
<p><span class="math display">\[TC = FC + VC\]</span></p>
<p><em>Hotel</em>: everything combined</p>
</div></div>
<p>. . .</p>
<p><span class="emoji" data-emoji="warning">⚠️</span> <strong>Important</strong>: FC is a <strong>sunk cost</strong> in the short run — it cannot be recovered. Remember Lecture 3!</p>
</div>
</section>
<section id="a-worked-example-algarve-beach-bar" class="slide level2">
<h2>A Worked Example: Algarve Beach Bar <span class="emoji" data-emoji="beach_umbrella">🏖️</span></h2>
<div style="font-size: 68%;">
<p>Imagine a small beach bar in Albufeira. The owner pays <strong>€500/month</strong> in rent (fixed), and hires staff and buys supplies (variable).</p>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Output (Q)</th>
<th style="text-align: center;">Fixed Cost (FC)</th>
<th style="text-align: center;">Variable Cost (VC)</th>
<th style="text-align: center;">Total Cost (TC = FC + VC)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: center;">€500</td>
<td style="text-align: center;">€0</td>
<td style="text-align: center;">€500</td>
</tr>
<tr class="even">
<td style="text-align: center;">50</td>
<td style="text-align: center;">€500</td>
<td style="text-align: center;">€200</td>
<td style="text-align: center;">€700</td>
</tr>
<tr class="odd">
<td style="text-align: center;">100</td>
<td style="text-align: center;">€500</td>
<td style="text-align: center;">€350</td>
<td style="text-align: center;">€850</td>
</tr>
<tr class="even">
<td style="text-align: center;">150</td>
<td style="text-align: center;">€500</td>
<td style="text-align: center;">€550</td>
<td style="text-align: center;">€1,050</td>
</tr>
<tr class="odd">
<td style="text-align: center;">200</td>
<td style="text-align: center;">€500</td>
<td style="text-align: center;">€800</td>
<td style="text-align: center;">€1,300</td>
</tr>
<tr class="even">
<td style="text-align: center;">250</td>
<td style="text-align: center;">€500</td>
<td style="text-align: center;">€1,150</td>
<td style="text-align: center;">€1,650</td>
</tr>
<tr class="odd">
<td style="text-align: center;">300</td>
<td style="text-align: center;">€500</td>
<td style="text-align: center;">€1,650</td>
<td style="text-align: center;">€2,150</td>
</tr>
</tbody>
</table>
<p><em>Output = drinks served per month (hypothetical illustrative example)</em></p>
<p><span class="emoji" data-emoji="point_right">👉</span> Notice: <strong>FC stays at €500</strong> always. <strong>VC increases</strong> — and it increases <strong>faster and faster</strong> (diminishing returns to the staff in the small bar!).</p>
</div>
</section>
<section id="plotting-the-total-cost-curves" class="slide level2">
<h2>Plotting the Total Cost Curves <span class="emoji" data-emoji="bar_chart">📊</span></h2>
<div style="font-size: 75%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="lecture10-costs_files/figure-revealjs/unnamed-chunk-2-1.png" class="quarto-figure quarto-figure-center" width="1056"></p>
</figure>
</div>
</div>
</div>
<p><span class="emoji" data-emoji="point_right">👉</span> <strong>TC and VC have the same shape</strong> — TC is just VC shifted <strong>up by FC</strong>. The vertical gap between TC and VC is always exactly <strong>€500</strong> (the fixed cost).</p>
</div>
</section></section>
<section>
<section id="average-and-marginal-costs" class="title-slide slide level1 center">
<h1>Average and Marginal Costs</h1>

</section>
<section id="why-averages-matter" class="slide level2">
<h2>Why Averages Matter <span class="emoji" data-emoji="thinking">🤔</span></h2>
<div style="font-size: 80%;">
<p>Total costs tell us the <strong>whole bill</strong>, but firms need to know the <strong>cost per unit</strong> to set prices and make decisions.</p>
<div class="key-concept">
<p><strong>Average Costs</strong></p>
<p><span class="math display">\[AFC = \frac{FC}{Q} \qquad AVC = \frac{VC}{Q} \qquad ATC = \frac{TC}{Q} = AFC + AVC\]</span></p>
</div>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Average Fixed Cost (AFC)</strong>:</p>
<ul>
<li>FC spread over more units</li>
<li><strong>Always falls</strong> as Q increases</li>
<li><span class="emoji" data-emoji="hotel">🏨</span> A hotel’s mortgage cost per guest falls as occupancy rises</li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>Average Variable Cost (AVC)</strong>:</p>
<ul>
<li>Variable cost per unit</li>
<li>Falls first, then <strong>rises</strong> (due to diminishing returns)</li>
<li><span class="emoji" data-emoji="fork_and_knife">🍴</span> Food cost per meal — efficient at moderate volume, rising when kitchen is overloaded</li>
</ul>
</div></div>
</div>
</section>
<section id="marginal-cost-the-most-important-curve" class="slide level2">
<h2>Marginal Cost: The Most Important Curve <span class="emoji" data-emoji="star">⭐</span></h2>
<div style="font-size: 80%;">
<div class="key-concept">
<p><strong>Marginal Cost (MC)</strong></p>
<p>The <strong>additional cost</strong> of producing <strong>one more unit</strong> of output.</p>
<p><span class="math display">\[MC = \frac{\Delta TC}{\Delta Q} = \frac{\text{Change in Total Cost}}{\text{Change in Output}}\]</span></p>
<p>Equivalently: <span class="math inline">\(MC = \frac{\Delta VC}{\Delta Q}\)</span> (since FC doesn’t change!)</p>
</div>
<p><strong>Intuition</strong>: If producing 100 drinks costs €850 total and producing 101 drinks costs €856, then <span class="math inline">\(MC = €6\)</span>.</p>
<p><strong>Why is MC so important?</strong></p>
<ul>
<li>It tells the firm whether producing one more unit <strong>adds to or subtracts from</strong> profit</li>
<li>Rule of thumb: <strong>produce more if the price you receive &gt; MC</strong></li>
<li>MC is the <strong>foundation of the supply curve</strong> (Lectures 12–14)</li>
</ul>
</div>
</section>
<section id="computing-averages-and-mc-beach-bar" class="slide level2">
<h2>Computing Averages and MC: Beach Bar <span class="emoji" data-emoji="pencil2">✏️</span></h2>
<div style="font-size: 62%;">
<table class="caption-top">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Q</th>
<th style="text-align: center;">FC</th>
<th style="text-align: center;">VC</th>
<th style="text-align: center;">TC</th>
<th style="text-align: center;">AFC = FC/Q</th>
<th style="text-align: center;">AVC = VC/Q</th>
<th style="text-align: center;">ATC = TC/Q</th>
<th style="text-align: center;">MC = ΔTC/ΔQ</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: center;">500</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">500</td>
<td style="text-align: center;">—</td>
<td style="text-align: center;">—</td>
<td style="text-align: center;">—</td>
<td style="text-align: center;">—</td>
</tr>
<tr class="even">
<td style="text-align: center;">50</td>
<td style="text-align: center;">500</td>
<td style="text-align: center;">200</td>
<td style="text-align: center;">700</td>
<td style="text-align: center;">10.00</td>
<td style="text-align: center;">4.00</td>
<td style="text-align: center;">14.00</td>
<td style="text-align: center;">4.00</td>
</tr>
<tr class="odd">
<td style="text-align: center;">100</td>
<td style="text-align: center;">500</td>
<td style="text-align: center;">350</td>
<td style="text-align: center;">850</td>
<td style="text-align: center;">5.00</td>
<td style="text-align: center;">3.50</td>
<td style="text-align: center;">8.50</td>
<td style="text-align: center;">3.00</td>
</tr>
<tr class="even">
<td style="text-align: center;">150</td>
<td style="text-align: center;">500</td>
<td style="text-align: center;">550</td>
<td style="text-align: center;">1,050</td>
<td style="text-align: center;">3.33</td>
<td style="text-align: center;">3.67</td>
<td style="text-align: center;">7.00</td>
<td style="text-align: center;">4.00</td>
</tr>
<tr class="odd">
<td style="text-align: center;">200</td>
<td style="text-align: center;">500</td>
<td style="text-align: center;">800</td>
<td style="text-align: center;">1,300</td>
<td style="text-align: center;">2.50</td>
<td style="text-align: center;">4.00</td>
<td style="text-align: center;">6.50</td>
<td style="text-align: center;">5.00</td>
</tr>
<tr class="even">
<td style="text-align: center;">250</td>
<td style="text-align: center;">500</td>
<td style="text-align: center;">1,150</td>
<td style="text-align: center;">1,650</td>
<td style="text-align: center;">2.00</td>
<td style="text-align: center;">4.60</td>
<td style="text-align: center;">6.60</td>
<td style="text-align: center;">7.00</td>
</tr>
<tr class="odd">
<td style="text-align: center;">300</td>
<td style="text-align: center;">500</td>
<td style="text-align: center;">1,650</td>
<td style="text-align: center;">2,150</td>
<td style="text-align: center;">1.67</td>
<td style="text-align: center;">5.50</td>
<td style="text-align: center;">7.17</td>
<td style="text-align: center;">10.00</td>
</tr>
</tbody>
</table>
<p><em>Hypothetical illustrative example</em></p>
<p><span class="emoji" data-emoji="point_right">👉</span> <strong>Key observations</strong>:</p>
<ul>
<li><strong>AFC</strong> always falls (spreading the fixed cost)</li>
<li><strong>AVC</strong> falls then rises (U-shaped) — minimum at Q = 100 (AVC = €3.50)</li>
<li><strong>ATC</strong> falls then rises (U-shaped) — minimum at Q = 200 (ATC = €6.50)</li>
<li><strong>MC</strong> falls then rises — and <strong>crosses AVC and ATC at their minimums</strong>!</li>
</ul>
</div>
</section>
<section id="the-geometry-of-costs" class="slide level2">
<h2>The Geometry of Costs <span class="emoji" data-emoji="triangular_ruler">📐</span></h2>

<img data-src="lecture10-costs_files/figure-revealjs/unnamed-chunk-3-1.png" class="quarto-figure quarto-figure-center r-stretch" width="1152"></section>
<section id="why-does-mc-cross-avc-and-atc-at-their-minimums" class="slide level2">
<h2>Why Does MC Cross AVC and ATC at Their Minimums? <span class="emoji" data-emoji="bulb">💡</span></h2>
<div style="font-size: 78%;">
<p>Think of it like your <strong>grade point average</strong> <span class="emoji" data-emoji="mortar_board">🎓</span></p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>The “exam grade” analogy</strong>:</p>
<ul>
<li>Your <strong>average grade</strong> = ATC (or AVC)</li>
<li>Your <strong>next exam grade</strong> = MC</li>
</ul>
<p>If your next exam grade is <strong>below</strong> your average → your average <strong>falls</strong> <span class="emoji" data-emoji="arrow_down">⬇️</span></p>
<p>If your next exam grade is <strong>above</strong> your average → your average <strong>rises</strong> <span class="emoji" data-emoji="arrow_up">⬆️</span></p>
<p>If your next exam grade <strong>equals</strong> your average → average <strong>stays the same</strong> (minimum!)</p>
</div><div class="column" style="width:50%;">
<p><strong>Applied to costs</strong>:</p>
<ul>
<li>When <span class="math inline">\(MC &lt; AVC\)</span> → AVC is <strong>falling</strong> <span class="emoji" data-emoji="arrow_down">⬇️</span></li>
<li>When <span class="math inline">\(MC &gt; AVC\)</span> → AVC is <strong>rising</strong> <span class="emoji" data-emoji="arrow_up">⬆️</span></li>
<li>When <span class="math inline">\(MC = AVC\)</span> → AVC is at its <strong>minimum</strong></li>
</ul>
<p>Same logic applies to ATC!</p>
<p><span class="emoji" data-emoji="point_right">👉</span> <strong>MC always crosses average curves at their lowest point.</strong></p>
<p>This is a <strong>mathematical fact</strong>, not an economic assumption.</p>
</div></div>
</div>
</section>
<section id="the-shapes-you-must-know" class="slide level2">
<h2>The Shapes You Must Know <span class="emoji" data-emoji="art">🎨</span></h2>
<div style="font-size: 75%;">
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Total Cost Curves</strong>:</p>
<ul>
<li><strong>FC</strong>: Horizontal line (constant)</li>
<li><strong>VC</strong>: Starts at origin, S-shaped (first rises slowly, then steeply)</li>
<li><strong>TC</strong>: VC shifted up by FC (same S-shape)</li>
</ul>
<p>The S-shape comes from diminishing returns — costs eventually accelerate.</p>
</div><div class="column" style="width:50%;">
<p><strong>Per-Unit Cost Curves</strong>:</p>
<ul>
<li><strong>AFC</strong>: Always declining (hyperbola)</li>
<li><strong>AVC</strong>: U-shaped (falls then rises)</li>
<li><strong>ATC</strong>: U-shaped, above AVC (the gap is AFC)</li>
<li><strong>MC</strong>: U-shaped, crosses AVC and ATC at their minimums</li>
</ul>
<p><span class="emoji" data-emoji="point_right">👉</span> As Q grows, ATC gets closer to AVC because AFC shrinks.</p>
</div></div>
<p>. . .</p>
<p><span class="emoji" data-emoji="warning">⚠️</span> <strong>Don’t confuse</strong>: MC can be <strong>below</strong> ATC while ATC is still <strong>falling</strong>. ATC rises only after MC <strong>crosses above</strong> it.</p>
</div>
</section></section>
<section>
<section id="tourism-application" class="title-slide slide level1 center">
<h1>Tourism Application</h1>

</section>
<section id="costs-in-the-hotel-industry" class="slide level2">
<h2>Costs in the Hotel Industry <span class="emoji" data-emoji="hotel">🏨</span></h2>
<div style="font-size: 75%;">
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Fixed costs</strong> (don’t change with occupancy):</p>
<ul>
<li><span class="emoji" data-emoji="house">🏠</span> Mortgage / building lease</li>
<li><span class="emoji" data-emoji="shield">🛡️</span> Insurance</li>
<li><span class="emoji" data-emoji="receipt">🧾</span> Property tax</li>
<li><span class="emoji" data-emoji="computer">💻</span> Booking system software license</li>
<li><span class="emoji" data-emoji="man_in_tuxedo">🤵‍♂️</span> Core management salaries</li>
<li><span class="emoji" data-emoji="hammer_and_wrench">🛠️</span> Scheduled maintenance</li>
</ul>
<p>These costs explain why hotels hate <strong>empty rooms</strong> — FC is already committed!</p>
</div><div class="column" style="width:50%;">
<p><strong>Variable costs</strong> (change with occupancy):</p>
<ul>
<li><span class="emoji" data-emoji="soap">🧼</span> Cleaning and laundry per room</li>
<li><span class="emoji" data-emoji="electric_plug">🔌</span> Energy and water per guest</li>
<li><span class="emoji" data-emoji="croissant">🥐</span> Breakfast/meal supplies</li>
<li><span class="emoji" data-emoji="bed">🛏️</span> Linen and amenity replacement</li>
<li><span class="emoji" data-emoji="busts_in_silhouette">👥</span> Part-time/seasonal staff</li>
</ul>
<p><strong>That’s why hotels offer last-minute discounts</strong> — as long as <span class="math inline">\(P &gt; MC\)</span> of hosting one more guest, it’s worth it!</p>
</div></div>
<p>. . .</p>
<p><span class="emoji" data-emoji="bulb">💡</span> The difference between FC and VC explains why <strong>low-season pricing</strong> exists: covering variable costs and <strong>some</strong> fixed costs is better than covering <strong>none</strong>.</p>
</div>
</section>
<section id="spreading-fixed-costs-why-airlines-overbook" class="slide level2">
<h2>Spreading Fixed Costs: Why Airlines Overbook <span class="emoji" data-emoji="airplane">✈️</span></h2>
<div style="font-size: 78%;">
<p><strong>The airline cost structure</strong> (illustrative):</p>
<p>An Algarve charter flight has roughly:</p>
<ul>
<li><span class="emoji" data-emoji="lock">🔒</span> <strong>High fixed costs</strong>: aircraft lease, crew salaries, airport fees, fuel (mostly fixed per flight)</li>
<li><span class="emoji" data-emoji="arrows_counterclockwise">🔄</span> <strong>Low variable costs per passenger</strong>: meals, baggage handling, marginal fuel</li>
</ul>
<p>. . .</p>
<div class="key-concept">
<p><strong>Spreading the Fixed Cost</strong></p>
<p>If a flight costs €20,000 to operate (mostly fixed) and has 200 seats:</p>
<ul>
<li><strong>100 passengers</strong>: AFC = €200/passenger</li>
<li><strong>150 passengers</strong>: AFC = €133/passenger</li>
<li><strong>200 passengers</strong>: AFC = €100/passenger</li>
</ul>
<p>Every additional passenger <strong>dramatically lowers</strong> the cost per passenger!</p>
</div>
<p><span class="emoji" data-emoji="point_right">👉</span> This is why airlines practice <strong>overbooking</strong> and <strong>dynamic pricing</strong> — filling seats spreads the enormous fixed cost.</p>
</div>
</section></section>
<section>
<section id="long-run-costs" class="title-slide slide level1 center">
<h1>Long Run Costs</h1>

</section>
<section id="in-the-long-run-everything-is-variable" class="slide level2">
<h2>In the Long Run, Everything is Variable <span class="emoji" data-emoji="unlock">🔓</span></h2>
<div style="font-size: 78%;">
<p>In the <strong>long run</strong>, the firm can adjust <strong>all</strong> inputs — including building size, number of machines, and technology.</p>
<div class="key-concept">
<p><strong>Long-Run Average Cost (LRAC)</strong></p>
<p>The lowest possible average cost for each level of output, when the firm is free to choose the <strong>optimal scale</strong> (size) of operations.</p>
</div>
<p>Think of it this way:</p>
<ul>
<li><strong>Short run</strong>: “Given our current hotel (100 rooms), what’s our cost?”</li>
<li><strong>Long run</strong>: “What <strong>size of hotel</strong> minimizes our cost per guest?”</li>
</ul>
<p>The LRAC curve is formed by choosing the <strong>best short-run plant size</strong> for each output level.</p>
<p><span class="emoji" data-emoji="point_right">👉</span> The LRAC is the <strong>“envelope”</strong> of all possible short-run ATC curves.</p>
</div>
</section>
<section id="the-envelope-lrac-as-the-best-of-all-short-runs" class="slide level2">
<h2>The Envelope: LRAC as the Best of All Short Runs <span class="emoji" data-emoji="love_letter">💌</span></h2>
<div style="font-size: 72%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="lecture10-costs_files/figure-revealjs/unnamed-chunk-4-1.png" class="quarto-figure quarto-figure-center" width="1152"></p>
</figure>
</div>
</div>
</div>
<p>Each dashed curve = one plant size (short run). The <strong>bold red LRAC</strong> = lowest cost achievable at each Q.</p>
<p><span class="emoji" data-emoji="point_right">👉</span> In the long run, the firm <strong>chooses the plant size</strong> that minimizes cost for its desired output.</p>
</div>
</section>
<section id="economies-and-diseconomies-of-scale" class="slide level2">
<h2>Economies and Diseconomies of Scale <span class="emoji" data-emoji="balance_scale">⚖️</span></h2>
<div style="font-size: 76%;">
<p>The shape of the LRAC curve reveals three zones:</p>
<div class="columns">
<div class="column" style="width:33%;">
<p><span class="emoji" data-emoji="arrow_down">⬇️</span> <strong>Economies of Scale</strong></p>
<p>LRAC is <strong>falling</strong></p>
<p>Bigger → cheaper per unit</p>
<p><strong>Tourism</strong>: Large hotel chains get bulk discounts, shared booking platforms, brand recognition</p>
<p><em>“Getting bigger makes us more efficient”</em></p>
</div><div class="column" style="width:34%;">
<p><span class="emoji" data-emoji="left_right_arrow">↔︎️</span> <strong>Constant Returns</strong></p>
<p>LRAC is <strong>flat</strong></p>
<p>Doubling inputs doubles output (cost per unit stays the same)</p>
<p><strong>Tourism</strong>: Mid-sized operators replicating a proven format across locations</p>
<p><em>“We’re at the right size”</em></p>
</div><div class="column" style="width:33%;">
<p><span class="emoji" data-emoji="arrow_up">⬆️</span> <strong>Diseconomies of Scale</strong></p>
<p>LRAC is <strong>rising</strong></p>
<p>Bigger → more expensive per unit</p>
<p><strong>Tourism</strong>: Huge resorts with bureaucracy, coordination problems, slow decision-making</p>
<p><em>“We’ve grown too big”</em></p>
</div></div>
<p>. . .</p>
<p><span class="emoji" data-emoji="bulb">💡</span> <strong>Minimum Efficient Scale (MES)</strong>: the smallest output where LRAC reaches its minimum. Firms should aim to operate <strong>at or beyond</strong> this point.</p>
</div>
</section>
<section id="economies-of-scale-in-tourism-real-world-logic" class="slide level2">
<h2>Economies of Scale in Tourism: Real-World Logic <span class="emoji" data-emoji="globe_with_meridians">🌐</span></h2>
<div style="font-size: 76%;">
<p><strong>Why do big hotel chains (Marriott, Accor, Hilton) have cost advantages?</strong></p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Sources of economies of scale</strong> <span class="emoji" data-emoji="arrow_down">⬇️</span>:</p>
<ul>
<li><span class="emoji" data-emoji="handshake">🤝</span> <strong>Bulk purchasing</strong>: negotiate lower prices with suppliers (linens, food, amenities)</li>
<li><span class="emoji" data-emoji="computer">💻</span> <strong>Technology</strong>: one central booking system serves thousands of properties</li>
<li><span class="emoji" data-emoji="tv">📺</span> <strong>Marketing</strong>: global advertising cost spread over many hotels</li>
<li><span class="emoji" data-emoji="mortar_board">🎓</span> <strong>Training</strong>: standardized programs cheaper per employee</li>
<li><span class="emoji" data-emoji="chart_with_upwards_trend">📈</span> <strong>Financing</strong>: large firms borrow at lower interest rates</li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>Why not grow forever?</strong> <span class="emoji" data-emoji="arrow_up">⬆️</span></p>
<ul>
<li><span class="emoji" data-emoji="snail">🐌</span> <strong>Bureaucracy</strong>: decisions take longer in large organizations</li>
<li><span class="emoji" data-emoji="speech_balloon">💬</span> <strong>Communication</strong>: harder to coordinate across 8,000+ properties</li>
<li><span class="emoji" data-emoji="broken_heart">💔</span> <strong>Loss of local identity</strong>: cookie-cutter hotels may lose appeal</li>
<li><span class="emoji" data-emoji="money_with_wings">💸</span> <strong>Monitoring costs</strong>: ensuring quality across locations</li>
</ul>
<p><span class="emoji" data-emoji="point_right">👉</span> This is why <strong>boutique hotels</strong> can survive alongside chains — they operate efficiently at a smaller scale with a different value proposition.</p>
</div></div>
</div>
</section></section>
<section>
<section id="putting-it-all-together" class="title-slide slide level1 center">
<h1>Putting It All Together</h1>

</section>
<section id="summary-of-cost-curves" class="slide level2">
<h2>Summary of Cost Curves <span class="emoji" data-emoji="clipboard">📋</span></h2>
<div style="font-size: 70%;">
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Concept</th>
<th>Formula</th>
<th>Shape</th>
<th>Key Fact</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Fixed Cost (FC)</strong></td>
<td>Constant</td>
<td>Horizontal line</td>
<td>Doesn’t change with output</td>
</tr>
<tr class="even">
<td><strong>Variable Cost (VC)</strong></td>
<td>Changes with Q</td>
<td>S-shaped (rises, accelerates)</td>
<td>Due to diminishing returns</td>
</tr>
<tr class="odd">
<td><strong>Total Cost (TC)</strong></td>
<td>FC + VC</td>
<td>VC shifted up by FC</td>
<td></td>
</tr>
<tr class="even">
<td><strong>Avg Fixed Cost (AFC)</strong></td>
<td>FC / Q</td>
<td>Always declining</td>
<td>Spreading the overhead</td>
</tr>
<tr class="odd">
<td><strong>Avg Variable Cost (AVC)</strong></td>
<td>VC / Q</td>
<td>U-shaped</td>
<td>Min where MC crosses it</td>
</tr>
<tr class="even">
<td><strong>Avg Total Cost (ATC)</strong></td>
<td>TC / Q = AFC + AVC</td>
<td>U-shaped (above AVC)</td>
<td>Gap to AVC = AFC (shrinks)</td>
</tr>
<tr class="odd">
<td><strong>Marginal Cost (MC)</strong></td>
<td>ΔTC / ΔQ</td>
<td>U-shaped</td>
<td>Crosses AVC &amp; ATC at their mins</td>
</tr>
<tr class="even">
<td><strong>LRAC</strong></td>
<td>Envelope of SRATCs</td>
<td>U-shaped</td>
<td>Economies → constant → diseconomies</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="summary" class="slide level2">
<h2>Summary <span class="emoji" data-emoji="memo">📝</span></h2>
<div style="font-size: 76%;">
<p><strong>Today’s Key Takeaways</strong>:</p>
<ol type="1">
<li><strong>Short run</strong>: at least one input is fixed; <strong>Long run</strong>: all inputs are variable</li>
<li><strong>Total costs</strong>: <span class="math inline">\(TC = FC + VC\)</span> — fixed costs don’t depend on output</li>
<li><strong>Average costs</strong>: ATC = AFC + AVC — both per-unit measures</li>
<li><strong>Marginal cost</strong>: the extra cost of one more unit — <strong>the most important curve</strong></li>
<li><strong>MC crosses AVC and ATC at their minimums</strong> (the “exam grade” rule)</li>
<li><strong>LRAC</strong>: the envelope of short-run ATC curves — shows optimal plant size</li>
<li><strong>Economies of scale</strong> explain why large hotel chains exist; <strong>diseconomies</strong> explain why they don’t grow forever</li>
</ol>
<p><strong>Connection</strong>: Costs are the <strong>foundation</strong> of supply. Next lecture we use MC to find the <strong>profit-maximizing output</strong>.</p>
<p><strong>Next (Lecture 11, March 20)</strong>: Companies — Profit Maximization <span class="emoji" data-emoji="moneybag">💰</span></p>
</div>
</section>
<section id="exercises" class="slide level2 center">
<h2>Exercises</h2>
<p><strong>Practice Time!</strong> <span class="emoji" data-emoji="pencil2">✏️</span></p>
<p>Cost curves, short run, and long run.</p>
</section>
<section id="exercise-1-multiple-choice" class="slide level2">
<h2>Exercise 1: Multiple Choice</h2>
<div style="font-size: 82%;">
<p><strong>Question</strong>: A tour operator in Lisbon has monthly fixed costs of €10,000 (office lease, software) and variable costs that depend on the number of tours sold. Currently, they sell 200 tours per month with an ATC of €80 per tour. If they increase to 250 tours and ATC falls to €72 per tour, what can we conclude?</p>
<p>A. Marginal cost of the additional tours is below €72</p>
<p>B. Marginal cost of the additional tours is above €80</p>
<p>C. The firm is experiencing diseconomies of scale</p>
<p>D. Fixed costs have increased</p>
<div class="fragment">
<div class="highlight-box">
<p><strong>Answer: A</strong></p>
</div>
<p>If ATC is <strong>falling</strong> (from €80 to €72), it must be that MC is <strong>pulling the average down</strong>. From the “exam grade” analogy: if your average falls, the new grade must be <strong>below</strong> the current average. So <span class="math inline">\(MC &lt; ATC = €72\)</span> for those additional 50 tours.</p>
</div>
</div>
</section>
<section id="exercise-2-multiple-choice" class="slide level2">
<h2>Exercise 2: Multiple Choice</h2>
<div style="font-size: 82%;">
<p><strong>Question</strong>: In the short run, a small hotel in Sintra has fixed costs of €6,000/month. When occupancy rises from 80 to 90 guests/month, total costs rise from €14,000 to €15,500. What is the marginal cost per additional guest?</p>
<p>A. €150</p>
<p>B. €155</p>
<p>C. €172</p>
<p>D. €175</p>
<div class="fragment">
<div class="highlight-box">
<p><strong>Answer: A</strong></p>
</div>
<p><span class="math inline">\(MC = \frac{\Delta TC}{\Delta Q} = \frac{€15{,}500 - €14{,}000}{90 - 80} = \frac{€1{,}500}{10} = €150\)</span> per guest.</p>
<p>Note: FC (€6,000) is <strong>irrelevant</strong> to MC — it doesn’t change! Only variable costs drive the change in TC.</p>
</div>
</div>
</section>
<section id="exercise-3-open-question" class="slide level2">
<h2>Exercise 3: Open Question <span class="emoji" data-emoji="writing_hand">✍️</span></h2>
<div style="font-size: 66%;">
<p><strong>A small surf school in Ericeira</strong> has monthly fixed costs of €2,000 (equipment rental, insurance) and the following cost structure:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">Students/month (Q)</th>
<th style="text-align: center;">Variable Cost (VC)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: center;">€0</td>
</tr>
<tr class="even">
<td style="text-align: center;">10</td>
<td style="text-align: center;">€800</td>
</tr>
<tr class="odd">
<td style="text-align: center;">20</td>
<td style="text-align: center;">€1,400</td>
</tr>
<tr class="even">
<td style="text-align: center;">30</td>
<td style="text-align: center;">€1,900</td>
</tr>
<tr class="odd">
<td style="text-align: center;">40</td>
<td style="text-align: center;">€2,600</td>
</tr>
<tr class="even">
<td style="text-align: center;">50</td>
<td style="text-align: center;">€3,500</td>
</tr>
<tr class="odd">
<td style="text-align: center;">60</td>
<td style="text-align: center;">€4,800</td>
</tr>
</tbody>
</table>
<p><strong>a)</strong> Calculate TC, AFC, AVC, ATC, and MC for each output level.</p>
<p><strong>b)</strong> At what output level is AVC minimized? At what output is ATC minimized?</p>
<p><strong>c)</strong> Verify that MC = AVC at the minimum of AVC, and MC = ATC at the minimum of ATC.</p>
<p><strong>d)</strong> The school charges €90 per student. At what output level would you expect MC to equal this price? What does this tell us about the profit-maximizing output? (We’ll formalize this in the next lecture!)</p>
<p><strong>e)</strong> In the long run, the school considers expanding to a second location. Explain, using the concept of economies of scale, under what conditions this expansion would lower the cost per student.</p>
</div>
</section>
<section id="exercise-3-solution-part-a" class="slide level2">
<h2>Exercise 3: Solution — Part a</h2>
<div style="font-size: 58%;">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">Q</th>
<th style="text-align: center;">FC</th>
<th style="text-align: center;">VC</th>
<th style="text-align: center;">TC</th>
<th style="text-align: center;">AFC</th>
<th style="text-align: center;">AVC</th>
<th style="text-align: center;">ATC</th>
<th style="text-align: center;">MC (per 10 students)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: center;">2,000</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">2,000</td>
<td style="text-align: center;">—</td>
<td style="text-align: center;">—</td>
<td style="text-align: center;">—</td>
<td style="text-align: center;">—</td>
</tr>
<tr class="even">
<td style="text-align: center;">10</td>
<td style="text-align: center;">2,000</td>
<td style="text-align: center;">800</td>
<td style="text-align: center;">2,800</td>
<td style="text-align: center;">200.00</td>
<td style="text-align: center;">80.00</td>
<td style="text-align: center;">280.00</td>
<td style="text-align: center;">80.00</td>
</tr>
<tr class="odd">
<td style="text-align: center;">20</td>
<td style="text-align: center;">2,000</td>
<td style="text-align: center;">1,400</td>
<td style="text-align: center;">3,400</td>
<td style="text-align: center;">100.00</td>
<td style="text-align: center;">70.00</td>
<td style="text-align: center;">170.00</td>
<td style="text-align: center;">60.00</td>
</tr>
<tr class="even">
<td style="text-align: center;">30</td>
<td style="text-align: center;">2,000</td>
<td style="text-align: center;">1,900</td>
<td style="text-align: center;">3,900</td>
<td style="text-align: center;">66.67</td>
<td style="text-align: center;">63.33</td>
<td style="text-align: center;">130.00</td>
<td style="text-align: center;">50.00</td>
</tr>
<tr class="odd">
<td style="text-align: center;">40</td>
<td style="text-align: center;">2,000</td>
<td style="text-align: center;">2,600</td>
<td style="text-align: center;">4,600</td>
<td style="text-align: center;">50.00</td>
<td style="text-align: center;">65.00</td>
<td style="text-align: center;">115.00</td>
<td style="text-align: center;">70.00</td>
</tr>
<tr class="even">
<td style="text-align: center;">50</td>
<td style="text-align: center;">2,000</td>
<td style="text-align: center;">3,500</td>
<td style="text-align: center;">5,500</td>
<td style="text-align: center;">40.00</td>
<td style="text-align: center;">70.00</td>
<td style="text-align: center;">110.00</td>
<td style="text-align: center;">90.00</td>
</tr>
<tr class="odd">
<td style="text-align: center;">60</td>
<td style="text-align: center;">2,000</td>
<td style="text-align: center;">4,800</td>
<td style="text-align: center;">6,800</td>
<td style="text-align: center;">33.33</td>
<td style="text-align: center;">80.00</td>
<td style="text-align: center;">113.33</td>
<td style="text-align: center;">130.00</td>
</tr>
</tbody>
</table>
<p><strong>MC calculation example</strong>: From Q = 20 to Q = 30: <span class="math inline">\(MC = \frac{3{,}900 - 3{,}400}{30 - 20} = \frac{500}{10} = €50\)</span> per student.</p>
</div>
</section>
<section id="exercise-3-solution-parts-b-c-d" class="slide level2">
<h2>Exercise 3: Solution — Parts b, c &amp; d</h2>
<div style="font-size: 68%;">
<p><strong>b)</strong> AVC is minimized at <strong>Q = 30</strong> (AVC = €63.33). ATC is minimized at <strong>Q = 50</strong> (ATC = €110.00).</p>
<p><span class="emoji" data-emoji="point_right">👉</span> AVC minimum comes <strong>before</strong> ATC minimum — this is always the case because AFC is still pulling ATC down even after AVC starts rising.</p>
<p><strong>c)</strong> At Q = 30 (AVC minimum): MC just shifted from €60 (at Q=20) to €50 (at Q=30), and then rises to €70 (at Q=40). MC passes through the AVC minimum range, consistent with theory. At Q = 50 (ATC minimum): MC = €90, while ATC = €110. Between Q=40 and Q=50, MC (€90) is still below ATC (€110), pulling it down. At Q=60, MC = €130 &gt; ATC = €113.33, so ATC starts rising. The crossing happens between Q=50 and Q=60. <span class="emoji" data-emoji="white_check_mark">✅</span></p>
<p><strong>d)</strong> Price = €90. MC = €90 at <strong>Q = 50</strong>. This suggests the profit-maximizing output is around <strong>50 students</strong>. At this level, each additional student brings in exactly as much revenue (€90) as they cost to add. Producing more (Q=60) would mean MC = €130 &gt; €90 = price → <strong>losing money on each extra student</strong>.</p>
</div>
</section>
<section id="exercise-3-solution-part-e" class="slide level2">
<h2>Exercise 3: Solution — Part e</h2>
<div style="font-size: 78%;">
<p><strong>e)</strong> Expanding to a second location would lower the cost per student if the school can achieve <strong>economies of scale</strong>:</p>
<ul>
<li><span class="emoji" data-emoji="handshake">🤝</span> <strong>Shared equipment purchases</strong>: buying boards and wetsuits in bulk at a discount</li>
<li><span class="emoji" data-emoji="computer">💻</span> <strong>Single booking/marketing system</strong> serving both locations</li>
<li><span class="emoji" data-emoji="mortar_board">🎓</span> <strong>Instructor training</strong>: standardized program developed once, used at both sites</li>
<li><span class="emoji" data-emoji="chart_with_upwards_trend">📈</span> <strong>Brand recognition</strong>: marketing costs spread over more students</li>
</ul>
<p><strong>However</strong>, expansion could also create <strong>diseconomies</strong> if:</p>
<ul>
<li>Coordination between locations is difficult (travel time, communication)</li>
<li>Quality control drops when the owner can’t supervise both sites</li>
<li>Each beach has unique conditions requiring different approaches</li>
</ul>
<p><span class="emoji" data-emoji="point_right">👉</span> Expansion makes sense if the LRAC <strong>falls</strong> at the combined output — that is, if the firm is still in the <strong>economies of scale</strong> region.</p>
</div>
</section>
<section id="next-lecture" class="slide level2 center">
<h2>Next Lecture</h2>
<p><strong>March 20, 2026</strong>: Companies — Profit Maximization <span class="emoji" data-emoji="moneybag">💰</span></p>
<p>How do firms use cost curves to choose the <strong>optimal output</strong>?</p>
<div class="fragment">
<p><span class="emoji" data-emoji="point_right">👉</span> <strong>Spoiler</strong>: The answer involves setting <strong>Price = MC</strong> in perfect competition!</p>
</div>
</section>
<section id="thank-you" class="slide level2 center">
<h2>Thank You!</h2>
<p><strong>Questions?</strong> <span class="emoji" data-emoji="raising_hand">🙋</span></p>
<p><span class="emoji" data-emoji="email">📧</span> paulo.fagandini@ext.universidadeeuropeia.pt</p>
</section>
<section class="slide level2">

<p><em>Next class: Friday, March 20, 2026</em></p>
<aside class="notes">
<p>This lecture introduces the full cost structure that underpins producer theory. Students should leave understanding that (1) costs have a clear geometry with predictable shapes, (2) MC is the key decision-making curve, and (3) the short run/long run distinction is about flexibility of inputs, not calendar time. The LRAC envelope concept connects to why tourism has both large chains and small operators. Next lecture builds directly on this to find the profit-maximizing output level.</p>
<style type="text/css">
        span.MJX_Assistive_MathML {
          position:absolute!important;
          clip: rect(1px, 1px, 1px, 1px);
          padding: 1px 0 0 0!important;
          border: 0!important;
          height: 1px!important;
          width: 1px!important;
          overflow: hidden!important;
          display:block!important;
      }</style></aside>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="../images/logo.png" class="slide-logo"></p>
<div class="footer footer-default">
<p>Economics of Tourism | Lecture 10</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1600,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>