---
title: "Material"
---

## Recommended Book

:book: [Shapiro, D.; MacDonald, D.; Greenlaw, S. A. (2022). Principles of Economics 3e. OpenStax.](https://openstax.org/details/books/principles-economics-3e)


## Slides

### Economics Fundamentals

1. [Introduction](slides/lecture01-intro.qmd) :page_facing_up: [PDF](PDF/lecture01-intro.pdf)
2. [Economic Systems](slides/lecture02-systems.qmd) :page_facing_up: [PDF](PDF/lecture02-systems.pdf)
3. [Opportunity Cost](slides/lecture03-opportunity.qmd) :page_facing_up: [PDF](PDF/lectrue03-opportunity.pdf)
4. [Production Possibility Frontier](slides/lecture04-ppf.qmd) :page_facing_up: [PDF](PDF/lecture04-ppf.pdf)

### Microeconomics

#### Consumer Theory: Behind the Demand

5. [Budget Set and Constraint](slides/lecture05-budget.qmd) :page_facing_up: [PDF](PDF/lecture05-budget.pdf)
6. [Preferences](slides/lecture06-preferences.qmd) :page_facing_up: [PDF](PDF/lecture06-preferences.pdf)
7. [MRS and Utility](slides/lecture07-mrs-utility.qmd) :page_facing_up: [PDF](PDF/lecture07-mrs-utility.pdf)
8. [Demand](slides/lecture08-demand.qmd) :page_facing_up: [PDF](PDF/lecture08-demand.pdf)
9. [Elasticity of Demand](slides/lecture09-elasticity.qmd) :page_facing_up: [PDF](PDF/lecture09-elasticity.pdf)


#### Producer Theory: Behind the Supply

10. [Costs](slides/lecture10-costs.qmd):page_facing_up: [PDF](PDF/lecture10-costs.pdf)
11. [Profit Maximization](slides/lecture11-profit-max.qmd):page_facing_up: [PDF](PDF/lecture11-profit-max.pdf)
12. [Supply](slides/lecture12-shutdown-supply.qmd):page_facing_up: [PDF](PDF/lecture12-shutdown-supply.pdf)
13. [Supply rule](slides/lecture13-supply-rule.qmd):page_facing_up: [PDF](PDF/lecture13-supply-rule.pdf)
14. [Producer Surplus and Market Supply](slides/lecture14-ps-market-supply.qmd):page_facing_up: [PDF](PDF/lecture14-ps-market-supply.pdf)
15. [Supply (and demand) Elasticity](slides/lecture15-supply-elasticity.qmd):page_facing_up: [PDF](PDF/lecture15-supply-elasticity.pdf)

#### Market Equilibrium and Game Theory

16. [Equilibrium](slides/lecture16-equilibrium.qmd):page_facing_up: [PDF](PDF/lecture16-equilibrium.pdf)
17. [Game Theory: Intro](slides/lecture18-game-theory.qmd):page_facing_up: [PDF](PDF/lecture18-game-theory.pdf)
18. [Game Theory: Sequential Games](slides/lecture19-sequential-games.qmd):page_facing_up: [PDF](PDF/lecture19-sequential-games.pdf)

### Macroeconomics

19. [Macroeconomic Issues](slides/lecture20-macro-issues.qmd):page_facing_up: [PDF](PDF/lecture20-macro-issues.pdf)
20. [Aggregation](slides/lecture21-aggregation.qmd):page_facing_up: [PDF](PDF/lecture21-aggregation.pdf)
21. [Gross Domestic Product](slides/lecture22-gdp.qmd):page_facing_up: [PDF](PDF/lecture22-gdp.pdf)
22. [Inflation](slides/lecture23-inflation.qmd):page_facing_up: [PDF](PDF/lecture23-inflation.pdf)
23. [Monetary Policy](slides/lecture24-monetary-policy.qmd):page_facing_up: [PDF](PDF/lecture24-monetary-policy.pdf)
24. [Fiscal Policy](slides/lecture25-fiscal-policy.qmd):page_facing_up: [PDF](PDF/lecture25-fiscal-policy.pdf)
25. [Balance of Payments](slides/lecture26-bop.qmd):page_facing_up: [PDF](PDF/lecture26-bop.pdf)